### ISSUE TITLE
Create base code for Movie hive front end

### ISSUE THREAD

**Issue by dasamantaraoaditya** [dasamantaraoaditya/watchhivefe#5]
Need to create basic code for anyone to work on movie hive front end
We can only start this ticket once we complete and have some basic understanding of which technical stack and what is the basic design to start with. https://github.com/dasamantaraoaditya/watchhivefe/issues/4
### Acceptance criteria
The base project to start with should be present in meoviehivefe repository

**Comment by dasamantaraoaditya** [comment]
@daredevilteja can start on this as we decided to have react as front end frame work.

**Comment by daredevilteja** [comment]
Created all the necessary starter code and added the readme for starting the project

**Comment by dasamantaraoaditya** [comment]
This looks good to me, i was able to run  and lunch the app in http://localhost:3000/ after above mentioned steps, if possible its better to keep the read.me simple.
